refator of pipelines

diff --git a/pipelines/toProd/Jenkinsfile b/pipelines/toProd/Jenkinsfile
--- a/pipelines/toProd/Jenkinsfile
+++ b/pipelines/toProd/Jenkinsfile
@@ -1,14 +1,24 @@
 pipeline {
     agent any
     
+    triggers {
+        githubPush()
+    }
+
+    options {
+        skipDefaultCheckout()
+        timeout(time: 60, unit: 'MINUTES') // Más tiempo para PROD por las pruebas Playwright
+        buildDiscarder(logRotator(numToKeepStr: '20'))
+    }
+
     environment {
         ORACLE_CONTAINER = "oracle-db"
         SQLCL_PATH       = "/opt/sqlcl/bin/sql"
         DB_CONN_STR      = "localhost:1521/FREEPDB1"
-        BUILD_DIR        = "/tmp/apex_project"
+        BUILD_DIR        = "/tmp/apex_project_prod"
         DB_USR           = "PROD_SCHEMA"
-        // URL de TEST para validación con Playwright
         APEX_TEST_URL    = "http://localhost:8181/ords/r/test_wrkspc_cicd/app-ci-cd"
+        MAIL_RECIPIENTS  = "sergiolucero73@gmail.com, slucero@runaid.com.ar"
     }
 
     stages {
@@ -111,9 +121,31 @@ EOF
     }
     
     post {
+        success {
+            script {
+                try {
+                    mail to: "${env.MAIL_RECIPIENTS}",
+                         subject: "Success: Pipeline ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+                         body: "¡ÉXITO! El despliegue en PRODUCCIÓN del pipeline ${env.JOB_NAME} #${env.BUILD_NUMBER} fue exitoso.\nLas pruebas de Playwright pasaron y el código está en PROD.\n\nVer detalles en: ${env.BUILD_URL}"
+                } catch (Exception e) {
+                    echo "Error enviando correo: ${e.message}"
+                }
+            }
+        }
+        failure {
+            script {
+                try {
+                    mail to: "${env.MAIL_RECIPIENTS}",
+                         subject: "Failure: Pipeline ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+                         body: "CRÍTICO: La ejecución del pipeline de PRODUCCIÓN #${env.BUILD_NUMBER} ha fallado.\n\nVer consola: ${env.BUILD_URL}console"
+                } catch (Exception e) {
+                    echo "Error enviando correo de fallo: ${e.message}"
+                }
+            }
+        }
         always {
             archiveArtifacts artifacts: 'artifact/*.zip, playwright-report/**', allowEmptyArchive: true
-            sh "docker exec -u root ${ORACLE_CONTAINER} rm -rf ${BUILD_DIR} /tmp/deploy_app.zip || true"
+            sh "docker exec -u root ${ORACLE_CONTAINER} rm -rf ${BUILD_DIR} || true"
         }
     }
 }
